# Problem 1

Joan says she is itchy. There is a test for Allergy to Cats, but this test is not always right:

* For people that really do have the allergy, the test says "Yes" 80% of the time
* For people that do not have the allergy, the test says "Yes" 10% of the time

If 1% of the population has the allergy, and Joan's test says "Yes", what are the chances that Joan really has the allergy?

## Using Python with Synthetic Data

In [ ]:
# Import needed modules
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from fractions import Fraction

### Choose size of population

In [ ]:
n = 10_000
f"{n:,}"

'10,000'

### Empty data frame

In [ ]:
df = pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

### Create the population

In [ ]:
df.index = np.arange(n)
df[:5]

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

### Tag those who do have the allergy

In [ ]:
# initially, tag everyone as not having the allergy
df["has_allergy"] = "F"

# tag 1% as having the allergy
df.iloc[:n//100, df.columns.get_loc("has_allergy")] = "T"

# display the transition
df[n//100-5:n//100+5]

    has_allergy
95            T
96            T
97            T
98            T
99            T
100           F
101           F
102           F
103           F
104           F

In [ ]:
# display frequency
df[["has_allergy"]].value_counts(normalize=True)*100

has_allergy
F              99.0
T               1.0
Name: proportion, dtype: float64

In [ ]:
# display absolute counts
df[["has_allergy"]].value_counts()

has_allergy
F              9900
T               100
Name: count, dtype: int64

### Tag those that have a positive test

In [ ]:
# set everyone to negative
df["test"] = "neg"


# adjust 80% of those with allergies to "pos"
has_allergy = ( df["has_allergy"] == "T" )
ha_pos_idx = df[ has_allergy ].sample(frac=0.8).index
df.loc[ ha_pos_idx, "test" ] = "pos"


# adjust 10% of those without allergies to "pos"
has_allergy = ( df["has_allergy"] == "F" )
ha_pos_idx = df[ has_allergy ].sample(frac=0.1).index
df.loc[ ha_pos_idx, "test" ] = "pos"

In [ ]:
vc_ds = df.value_counts()
vc_ds

has_allergy  test
F            neg     8910
             pos      990
T            pos       80
             neg       20
Name: count, dtype: int64

#### Bayes

Calculate conditional and marginal probabilities.

In [ ]:
p_has_allergy = (vc_ds["T",:].sum())/n
p_has_allergy

np.float64(0.01)

In [ ]:
p_test_positive = (vc_ds[:,"pos"].sum())/n
p_test_positive

np.float64(0.107)

In [ ]:
p_test_pos_given_has_allergy = vc_ds["T","pos"]/(vc_ds["T",:]).sum()
p_test_pos_given_has_allergy

np.float64(0.8)

Assemble using Bayes theorem.

In [ ]:
p_has_allergy_given_test_post = p_test_pos_given_has_allergy * p_has_allergy / p_test_positive
p_has_allergy_given_test_post

np.float64(0.07476635514018692)

#### Calculate directly using counts.

In [ ]:
vc_pos = vc_ds[:,"pos"]
vc_pos

has_allergy
F    990
T     80
Name: count, dtype: int64

In [ ]:
vc_pos["T"]/(vc_pos[:]).sum()

np.float64(0.07476635514018691)

In [ ]:
80/(80+990)

0.07476635514018691